Repository aws-controllers-k8s/sns-controller, pull requests merged in 2023-04, with the labels that each got.

#27 release artifacts for release v0.0.11
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/platform_endpoint.go
  config/controller/kustomization.yaml
  config/crd/bases/sns.services.k8s.aws_platformendpoints.yaml
  helm/Chart.yaml
  helm/crds/sns.services.k8s.aws_platformendpoints.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm

#28 support updating tags for Topic
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/platform_endpoint.go
  config/crd/bases/sns.services.k8s.aws_platformendpoints.yaml
  generator.yaml
  helm/crds/sns.services.k8s.aws_platformendpoints.yaml
  pkg/resource/topic/delta.go
  pkg/resource/topic/hooks.go
  pkg/resource/topic/sdk.go
  pkg/util/tags.go
  templates/hooks/topic/sdk_get_attributes_post_set_output.go.tpl
  templates/hooks/topic/sdk_update_pre_build_request.go.tpl
  test/e2e/tests/test_topic.py
Labels: approved, lgtm

#29 Release artifacts for release `v0.0.12`
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/crds/services.k8s.aws_adoptedresources.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm

#31 implement set attributes for Topic
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/platform_endpoint.go
  apis/v1alpha1/topic.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/sns.services.k8s.aws_platformendpoints.yaml
  config/crd/bases/sns.services.k8s.aws_topics.yaml
  generator.yaml
  helm/crds/sns.services.k8s.aws_platformendpoints.yaml
  helm/crds/sns.services.k8s.aws_topics.yaml
  pkg/resource/topic/delta.go
  pkg/resource/topic/hooks.go
  pkg/resource/topic/manager.go
  pkg/resource/topic/sdk.go
  test/e2e/tests/test_topic.py
Labels: approved, lgtm

#25 removing dev preview from olm file
  olm/olmconfig.yaml
Labels: needs-ok-to-test

#32 support update code path for Subscription
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/subscription.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/sns.services.k8s.aws_subscriptions.yaml
  generator.yaml
  helm/crds/services.k8s.aws_adoptedresources.yaml
  helm/crds/sns.services.k8s.aws_subscriptions.yaml
  pkg/resource/subscription/delta.go
  pkg/resource/subscription/hooks.go
  pkg/resource/subscription/sdk.go
  test/e2e/tests/test_subscription.py
Labels: approved, lgtm

#30 Release artifacts for release `v1.0.0`
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm

#33 Add primary keys for generator
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  go.mod
  go.sum
  pkg/resource/platform_application/references.go
  pkg/resource/platform_application/resource.go
  pkg/resource/platform_endpoint/references.go
  pkg/resource/platform_endpoint/resource.go
  pkg/resource/subscription/references.go
  pkg/resource/subscription/resource.go
  pkg/resource/topic/references.go
  pkg/resource/topic/resource.go
Labels: approved, lgtm, ok-to-test

#34 Release artifact for release `v1.0.1`
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/crds/services.k8s.aws_adoptedresources.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
Labels: approved, lgtm
